wanderer-industries/wanderer

- assets/js/hooks/Mapper/components/mapInterface/widgets/RoutesWidget/RoutesWidget.tsx
- assets/js/hooks/Mapper/mapRootProvider/hooks/useLoadSystemStatic.ts
> fix(Map): add key for cache changes detecting

- config/runtime.exs
A provider requires TSL/SSL for the DB connection and I'm too lazy to work out how to get the CA mounted into the this provider's containers.
> Added DATABASE_SSL_VERIFY_NONE env var

- assets/js/hooks/Mapper/common-styles/prime-fixes/fix-dialog.scss
- assets/js/hooks/Mapper/common-styles/prime-fixes/theme.scss
- assets/js/hooks/Mapper/components/mapRootContent/MapRootContent.tsx
- assets/js/hooks/Mapper/components/mapRootContent/components/MapContextMenu/MapContextMenu.tsx
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/MapSettings.module.scss
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/MapSettings.tsx
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/components/PrettySwitchbox/MapSettings.module.scss
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/components/PrettySwitchbox/PrettySwitchbox.tsx
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/components/PrettySwitchbox/index.ts
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/components/index.ts
- assets/js/hooks/Mapper/components/mapRootContent/components/MapSettings/index.ts
- assets/js/hooks/Mapper/components/mapRootContent/components/RightBar/RightBar.tsx
- assets/js/hooks/Mapper/mapRootProvider/MapRootProvider.tsx
- assets/js/hooks/Mapper/types/mapHandlers.ts
> feat(Map): Prettify user settings

- lib/wanderer_app/api/map_character_settings.ex
- lib/wanderer_app/map/map_server_impl.ex
- lib/wanderer_app/repositories/map_character_settings_repo.ex
- lib/wanderer_app_web/live/characters/characters_tracking_live.ex
- lib/wanderer_app_web/live/maps/event_handlers/map_characters_event_handler.ex
- lib/wanderer_app_web/live/maps/event_handlers/map_core_event_handler.ex
- lib/wanderer_app_web/live/maps/maps_live.ex
> fix(Core): Untracked characters still tracked on map

- .github/workflows/build.yml
> hotfix: add ARM64 compatible Docker image

- .github/workflows/build.yml
Reverts wanderer-industries/wanderer#94
> Revert "hotfix: add ARM64 compatible Docker image"

- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignaturesContent/SystemSignaturesContent.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/constants.ts
- assets/js/hooks/Mapper/helpers/parseSignatures.ts
- assets/js/hooks/Mapper/types/signatures.ts
> fix(Map): Add support RU signatures and fix filtering

- assets/js/hooks/Mapper/components/map/Map.module.scss
- assets/js/hooks/Mapper/components/map/components/SolarSystemNode/SolarSystemNode.module.scss
- assets/js/hooks/Mapper/components/map/components/SolarSystemNode/SolarSystemNode.tsx
- assets/js/hooks/Mapper/components/map/hooks/useBackgroundVars.ts
- assets/js/hooks/Mapper/components/map/styles/neon-theme.scss
- assets/js/hooks/Mapper/components/map/styles/pathfinder-theme.scss
- assets/js/hooks/Mapper/components/mapInterface/widgets/RoutesWidget/RoutesList/RoutesList.module.scss
- also updates dark mode in default theme, and some pathfinder theme settings
> fix: fix route color

- assets/js/hooks/Mapper/components/map/hooks/useBackgroundVars.ts
- assets/js/hooks/Mapper/components/map/hooks/useSolarSystemNode.ts
- also makes some additional variables available that may be useful for node related theme changes
> fix: support additional theme names

- .github/workflows/build.yml
- Dockerfile
Reviewed the GitHub actions error. Appears to be resolved when adding `+JPperf true` as a flag to the Elixir build.
> hotfix: ARM compatibility

- lib/wanderer_app_web/controllers/common_api_controller.ex
- lib/wanderer_app_web/controllers/map_api_controller.ex
- lib/wanderer_app_web/controllers/plugs/check_kills_disabled.ex
- lib/wanderer_app_web/controllers/util_api_controller.ex
- lib/wanderer_app_web/router.ex
- priv/posts/2025/01-05-map-public-api.md
Request
```
curl -H "Authorization: Bearer [REDACTED]" "https://wanderer.yourdomain.com/api/map/systems-kills?slug=yourmap"
```
Response
```
{
"data": [
{
"kills": [
{
"attacker_count": 1,
"final_blow_alliance_id": 99013806,
"final_blow_alliance_ticker": "TCE",
"final_blow_char_id": 2116802670,
"final_blow_char_name": "Bambi Bunny",
"final_blow_corp_id": 98140648,
"final_blow_corp_ticker": "GNK3D",
"final_blow_ship_name": "Thrasher",
"final_blow_ship_type_id": 16242,
"kill_time": "2025-01-21T21:00:59Z",
"killmail_id": 124181782,
"npc": false,
"solar_system_id": 30002768,
"total_value": 10000,
"victim_alliance_id": null,
"victim_char_id": 2121725410,
"victim_char_name": "Bill Drummond",
"victim_corp_id": 98753095,
"victim_corp_ticker": "KSTJK",
"victim_ship_name": "Capsule", …
```
> Add api for visible system kill information

- README.md
- assets/js/hooks/Mapper/components/mapInterface/widgets/LocalCharacters/LocalCharacters.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/components/CompactKillRow.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/components/FullKillRow.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/helpers/linkHelpers.ts
https://github.com/user-attachments/assets/3f9a7af5-0787-48b1-9074-46c49162afae
> fix: improve local character header shrink behavior

- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/SystemKills.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/SystemKillsContent/SystemKillsContent.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/components/SystemKillsSettingsDialog.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/hooks/useKillsWidgetSettings.ts
> feat: allow filtering of k-space kills

- assets/js/hooks/Mapper/components/ui-kit/CharacterCard/CharacterCard.tsx
> fix: color and formatting fixes for local character

- assets/js/hooks/Mapper/components/map/components/SolarSystemNode/SolarSystemLocalCounter.module.scss
- assets/js/hooks/Mapper/components/map/components/SolarSystemNode/SolarSystemLocalCounter.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/LocalCharacters/components/LocalCharactersList.tsx
> feat: autosize local character tooltip and increase hover target

- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignatureHeader/SystemSignatureHeader.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignatures.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/renders/index.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/renders/renderHeaderLabel.tsx
- current behavior matches original,, still have re-render for the time change, system, lazy delete
https://github.com/user-attachments/assets/53d1769f-492b-40bd-bcfd-90ea03bf35ec
> fix: prevent constant full signature widget rerender

- assets/js/hooks/Mapper/components/map/constants.ts
- assets/js/hooks/Mapper/components/mapInterface/components/SystemLinkSignatureDialog/SystemLinkSignatureDialog.tsx
- assets/js/hooks/Mapper/components/mapRootContent/components/SignatureSettings/SignatureSettings.tsx
- assets/js/hooks/Mapper/helpers/getWhSize.ts
Automatically updates wormhole connections both in the signature linking dialog and when manually editing with signature settings
> feat: Auto-set connection EOL status and ship size when linking/editing signatures

- assets/js/hooks/Mapper/components/map/constants.ts
- assets/js/hooks/Mapper/components/mapInterface/components/SystemLinkSignatureDialog/SystemLinkSignatureDialog.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/helpers/linkHelpers.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SignatureView/SignatureView.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignatureHeader/SystemSignatureHeader.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignatureSettingsDialog/SystemSignatureSettingsDialog.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignatures.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/SystemSignaturesContent/SystemSignaturesContent.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/constants.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/helpers/getActualSigs.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/helpers/getRowBackgroundColor.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/helpers/rowStyles.module.scss
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/helpers/rowStyles.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/hooks/types.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/hooks/usePendingAdditions.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/hooks/usePendingDeletions.ts
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/hooks/useSystemSignaturesData.ts
- assets/js/hooks/Mapper/helpers/getEveImageUrl.ts
- assets/js/hooks/Mapper/helpers/index.ts
https://github.com/user-attachments/assets/08e1eaca-6f81-4a50-8866-906736a8ae17
> feat: add selectable sig deletion timing, and color options

- assets/js/hooks/Mapper/components/map/components/SolarSystemNode/SolarSystemKillsCounter.tsx
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/SystemKillsContent/SystemKillsContent.module.scss
- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemKills/SystemKillsContent/SystemKillsContent.tsx
https://github.com/user-attachments/assets/46f276de-1ac2-4774-a77c-d0ff4cf0a747
> fix [kills]: prevent virtual scroller from showing unless needed

- lib/wanderer_app_web/router.ex
> fix: removed placeholder favicon

- lib/wanderer_app/vault.ex
Reverts wanderer-industries/wanderer#288
> Revert "fix: cloak key error behavior"

- lib/wanderer_app/api/map_character_settings.ex
- lib/wanderer_app_web/controllers/map_api_controller.ex
- lib/wanderer_app_web/router.ex
- **New Features**
- Added new API endpoints to fetch user characters and tracked characters for a specific map, accessible via either map UUID or slug.
- **Improvements**
- Enhanced API endpoints to support flexible map identification using both UUIDs and slugs.
- API responses now provide more structured and user-friendly JSON data for character settings.
- **Documentation**
- Updated API documentation to reflect new path parameters and improved response descriptions.
> fix: removed error from characters endpoint, and updated routes

- assets/js/hooks/Mapper/components/contexts/ContextMenuSystem/useContextMenuSystemItems.tsx
> fix(Map): Allow lock systems for members

- assets/js/hooks/Mapper/components/mapInterface/widgets/SystemSignatures/renders/renderInfoColumn.tsx
Reverts wanderer-industries/wanderer#501
> Revert "fix: default signature types not being shown"
